Fix issues for custom checkout

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,17 @@
 #! /bin/csh -f
 
+# system configuration for configure script
+set PERLBIN = ""
+
+if ($PERLBIN == "") then
+    if (-e configsdp.txt) then
+        # at stanford, use 
+        set PERLBIN = "/home/jsoc/bin/linux_x86_64/perl5.12.2"
+    else
+        set PERLBIN = "perl"
+    endif
+endif
+
 # set up $JSOC_MACHINE
 set JSOC_MACHINE = `build/jsoc_machine.csh`
 echo "Machine type is $JSOC_MACHINE"
@@ -8,20 +20,22 @@ echo ""
 set CLEAN = "no"
 set PROJCONFIG = ""
 set CLEANCMD = "d"
-set CONFIGCMD = "c"
-set LOCALIZE = "L"
 
 set CUSTOMDEFSFILE = ""
 
-foreach ARG ($argv)
-    set FLAG = `echo $ARG | awk '{print substr($0, 2, 1)}'`
-
+foreach THEARG ($argv)
+    set LITERALSTR = '{ my($argin) = "'${THEARG}'"; my($flagout); $flagout = ($argin =~ /^-(.+)/)[0]; print $flagout; }'
+    set FLAG = `$PERLBIN -e "$LITERALSTR"`
+    
     if ($FLAG == $CLEANCMD) then
-      set CLEAN = "yes"
-    else if ($FLAG == $CONFIGCMD) then
-      set PROJCONFIG = `echo $ARG | awk '{print substr($0, 3)}'`
+        set CLEAN = "yes"
+    else if (-e $THEARG) then
+        set PROJCONFIG = $THEARG
     endif
 end
+
+# Usage:
+#   configure [ -c ] [ <project config file> ]
 
 # Backward compatibility - remove the links to the old make files in projconf
 if (-d proj) then	 
@@ -182,11 +196,11 @@ endif
 
                 # run moreconfigure.pl - this script is written in perl because it is easier to do the compiler detection 
                 # in perl. It also reads configdsp.txt (if it exists) to set the default Stanford values for certain make variables
-                ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk -c${CUSTOMDEFSFILE}
+                $PERLBIN ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk -c${CUSTOMDEFSFILE}
 
                 # must follow moreconfigure.pl, because moreconfigure.pl will possibly set the compiler make variables,
                 # which are then referenced by lines in custom.mk generated by customizemake.pl.
-                ./customizemake.pl ./config.local ${LOCALIZATIONDIR}
+                $PERLBIN ./customizemake.pl ./config.local ${LOCALIZATIONDIR}
             endif
         else if (-e config.local) then
             # config.local is optional at Stanford, but it won't necessarily contain the same information that 
@@ -201,39 +215,49 @@ endif
             # items included in config.local to override those defined in serverdefs.h, but not all
             # items need be specified in config.local.
             echo "CUSTOM_DEFINES = __CUSTOMIZED_DEFS__" >> ${LOCALIZATIONDIR}/custom.mk
-            ./customizedefs.pl
+            $PERLBIN ./customizedefs.pl
 
             set CUSTOMDEFSFILE = "base/include/customizeddefs.h"
 
             # run moreconfigure.pl - this script is written in perl because it is easier to do the compiler detection 
             # in perl. It also reads configsdp.txt (if it exists) to set the default Stanford values for certain make variables
-            ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk -c${CUSTOMDEFSFILE}
+            $PERLBIN ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk -c${CUSTOMDEFSFILE}
 
             # update custom.mk with data from config.local
             # must follow moreconfigure.pl, because moreconfigure.pl will possibly set the compiler make variables,
             # which are then referenced by lines in custom.mk generated by customizemake.pl.
-            ./customizemake.pl ./config.local ${LOCALIZATIONDIR}
+            $PERLBIN ./customizemake.pl ./config.local ${LOCALIZATIONDIR}
         else
             # run moreconfigure.pl - this script is written in perl because it is easier to do the compiler detection 
             # in perl. It also reads configsdp.txt (if it exists) to set the default Stanford values for certain make variables
-            ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk 
+            $PERLBIN ./moreconfigure.pl -d${LOCALIZATIONDIR} -fcustom.mk 
+        endif
+
+        # Figure out if this is a custom checkout
+        set CUSTCO = "no"
+        set LITERALSTR = '{ open(CFG, "<'${LOCALIZATIONDIR}'/dlset.txt") || die "BAD"; my $line = <CFG>; chomp($line); print $line; }'
+        set CUSTCO = `$PERLBIN -e "$LITERALSTR"`
+
+        if (${CUSTCO} == "BAD") then
+            echo "Unable to open checkout state file ${LOCALIZATIONDIR}/dlset.txt"
+            exit 1
+        else if (${CUSTCO} == "custom") then
+            set CUSTCO = "yes"
         endif
 
         if (${PROJCONFIG} == "") then
+            if (${CUSTCO} == "yes") then
+                echo "Must provide configuration file as an argument to this configure script"
+                exit 1;
+            endif
             if (-e configsdp.txt) then
                 set PROJCONFIG = configsdp.txt
             endif
         endif
 
-        if (-e configsdp.txt) then
-            set PROJCONFIGEXE = "/home/jsoc/bin/linux_x86_64/perl5.12.2 configproj.pl"
-        else
-            set PROJCONFIGEXE = "configproj.pl"
-        endif
-
         if (${PROJCONFIG} != "") then
-            echo "Running project configuration [${PROJCONFIGEXE} -c${PROJCONFIG} -d${LOCALIZATIONDIR}]."
-            ${PROJCONFIGEXE} -c${PROJCONFIG} -d${LOCALIZATIONDIR}
+            echo "Running project configuration [${PERLBIN} configproj.pl -c${PROJCONFIG} -d${LOCALIZATIONDIR}]."
+            ${PERLBIN} configproj.pl -c${PROJCONFIG} -d${LOCALIZATIONDIR}
         endif
 
 	echo "Setting links to scripts..."
