Check for error when calling createtabstructure

diff --git a/base/drms/replication/subscribe_manage/sql_gen b/base/drms/replication/subscribe_manage/sql_gen
--- a/base/drms/replication/subscribe_manage/sql_gen
+++ b/base/drms/replication/subscribe_manage/sql_gen
@@ -216,7 +216,21 @@ do
 		logwrite "Executing [$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql]"
 		$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql
 
+    resp=$?
+
+    if [ "$resp" == "5" ]
+    then
+        logwrite "ERROR: Unknown series ${schema_table[$counter]}"
+        rm -f $input_file
+        exit 1
+    fi
+
+    if [ "$resp" != "0" ]
+        logwrite "ERROR: createtabstructure returned $resp"
+        rm -f $input_file
+        exit 1
 	fi
+
 	counter=$(( $counter + 1 ))
 done
 echo "new_site is $new_site"
