Integrate back into our cvs tree changes by Igor to fix synchronization issues surrounding the .lst file (although I replaced the original db lock mechanism with a fs-based one); fixed some new bugs that prevented subscribe from working with new subscriber sites; add conf parameters for merging replication sets, and managing the slon daemons to take care of anomolous log entries

diff --git a/base/drms/replication/subscribe_manage/sql_gen b/base/drms/replication/subscribe_manage/sql_gen
--- a/base/drms/replication/subscribe_manage/sql_gen
+++ b/base/drms/replication/subscribe_manage/sql_gen
@@ -1,6 +1,5 @@
 #!/bin/bash
 export LD_LIBRARY_PATH=/usr/local/pgsql/lib
-pidfile=$0.pid
 
 #--------------------------------------------------------------------
 # sql_gen
@@ -15,76 +14,24 @@ pidfile=$0.pid
 #-------------------------------------------------------------------------
 # syntax check
 #-------------------------------------------------------------------------
-if [ $# -eq 7 ]
+if [ $# -eq 6 ]
 then
-        config_file=$1
-	node=$2
-	new_site=$3
-	archive=$4
-	retention=$5
-	tapegroup=$6
-	input_file=$7
+#        config_file=$1
+	node=$1
+	new_site=$2
+	archive=$3
+	retention=$4
+	tapegroup=$5
+	input_file=$6
 else
-        error="ERROR: Usage: $0 <server configuration file> <node> <new subscription, true/false> <subscription information file>"
+        #error="ERROR: Usage: $0 <server configuration file> <node> <new subscription, true/false> <subscription information file>"
+        error="ERROR: Usage: $0 <node> <new subscription, true/false> <subscription information file>"
         echo $error
-	exit
+	exit 1
 fi
 
-. "$config_file"
-
-scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
-
-if [ -z "$kSMlogDir" ]
-then
-  logfile=../log/$scrbase.log
-else
-  logfile="$kSMlogDir/$scrbase.log"
-fi
-
-if [ -z "$kMaxLog" ]
-then
-  maxlog=1048576
-else
-  maxlog="$kMaxLog"
-fi
-
-if [ ! -f "$logfile" ]
-then
-  touch "$logfile"
-  if [ $? -ne 0 ]
-  then
-    logecho "Couldn't touch log file [$logfile] ... exiting."
-    exit 1;
-  fi
-else
-  # log exists, truncate if getting too big
-  sz=`stat -c%s $logfile`
-  if [ $sz -ge $maxlog ]
-  then
-    : > "$logfile"
-    if [ $? -ne 0 ]
-      then
-        logecho "Couldn't truncate log file [$logfile] ... exiting."
-      exit 1;
-    fi
-  fi
-fi
-
-
-#--------------------------------------------------------------------
-# Setting up the log
-#--------------------------------------------------------------------
-
-logwrite () {
-        echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
-        if [ ! $2 == "" ]
-        then
-                echo `date +"%m-%d-%Y %H:%M:%S - "` >> $logfile
-        fi
-}
 
 logwrite "Starting $0 $1" nl
-
 
 #------------------------------------------------------------------------
 # Checks to see if the schema and tables exist on the webdb
@@ -104,9 +51,13 @@ logwrite "Setting failure to 0"
 #unset check
 
 # remove all unsubscribe requests from input_file
-cat $input_file | grep -v "unsubscribe" > new_input_file.txt
-mv -f new_input_file.txt $input_file
-
+cat $input_file | grep -v "unsubscribe" > $SMworkDir/new_input_file.txt
+mv -f $SMworkDir/new_input_file.txt $input_file
+## 
+## see that input file now contains the PID of the process dealing with it
+## i.e. #UPDATE PID:<pid>
+## basically we are allowing comment lines in the file
+##
 exec < $input_file
 	while read line
 	do
@@ -114,6 +65,12 @@ exec < $input_file
                 if [ ${#line} -eq 0 ]
                 then
                 	continue
+                fi
+
+                # skips comment lines
+                if [ -z "${line%%#*}" ]
+                then
+			continue
                 fi
 
 		set - $line
@@ -148,8 +105,8 @@ if [ $failure -ne 0 ]
 then
 	# there was a failure, report failure, cleanup and exit
 	logwrite "Failure detected!"
-	logwrite "Failure process: Removing $node.subscribe_series.subupdate"
-	rm -f $node.subscribe_series.subupdate
+	logwrite "Failure process: Removing $input_file"
+	rm -f $input_file
 	logwrite "Failure process: Removing $triggerdir/$node.subscribe_series.cfg"
 	rm -f $triggerdir/$node.subscribe_series.cfg
 	logwrite "Failure process: removing $subscribers_dir/$node.new" 
@@ -160,8 +117,8 @@ then
 	cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
 	mv -f $parser_config.new $parser_config
 	logwrite "Failure process: Writing [failure] to $triggerdir/$node.subscribe_series.sqldone" 
-	echo "failure" > $triggerdir/$node.subscribe_series.sqldone
-	exit
+	echo "failure in sqlgen. Couldn't connect to db or series doesn't exists in DB" > $triggerdir/$node.subscribe_series.sqldone
+	exit 1
 fi
 
 #-------------------------------------------------------------------------
@@ -179,6 +136,12 @@ exec < $input_file
                 if [ ${#line} -eq 0 ]
                 then
                 	continue
+                fi
+
+                # skips comment lines
+                if [ -z "${line%%#*}" ]
+                then
+			continue
                 fi
 
 		set - $line
@@ -203,7 +166,7 @@ logwrite "Table list is [${table[@]}]"
 #-------------------------------------------------------------------------
 # Checks if there are any new subscriptions, if not, then skip createns, createtabstructure, and sdo_slony1_dump
 #-------------------------------------------------------------------------
-subcheck=`cat $input_file | grep -v "unsubscribe"`
+subcheck=`cat $input_file | grep -v "unsubscribe" | grep -vE "^#"`; ## remove unsubscribe lines and comment lines
 if [ "$subcheck" == "" ]
 then
 	logwrite "No new subscriptions, skipping createns, createtabstructure and sdo_slony1_dump" nl
@@ -227,6 +190,7 @@ do
 		# If first time finding this schema, execute ./createns
 		logwrite "Executing [$kModDir/createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER >> $triggerdir/$node.${schema[$counter]}.createns.sql]"
 		#echo "Createns >>" #remove
+
 		$kModDir/createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER > $triggerdir/$node.${schema[$counter]}.createns.sql
 		#echo "<<Createns" #remove
 		# echo ${schema[$counter]} >> $triggerdir/$node.createns.sql
@@ -250,9 +214,11 @@ do
 		# If first time finding this schema_table, execute ./createtabstruct
 		logwrite "Executing [$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql]"
 		$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql
+
 	fi
 	counter=$(( $counter + 1 ))
 done
+echo "new_site is $new_site"
 
 # Set $new_site to binary boolean
 if [ $new_site == "true" ]
@@ -263,61 +229,60 @@ else
 fi
 
 #-------------------------------------------------------------------------
-# Execute sdo_slony1_dump.sh
-#-------------------------------------------------------------------------
-logwrite "Executing: [ $kRepDir/subscribe_manage/sdo_slony1_dump.sh $SLAVEDBNAME jsoc $SLAVEPORT $new_site_bool ${schema_table[@]} >> $triggerdir/$node.subscribe_series.sql 2> $SMworkDir/slony1_dump.$node.log &"
-$kRepDir/subscribe_manage/sdo_slony1_dump.sh $SLAVEDBNAME jsoc $SLAVEPORT $new_site_bool ${schema_table[@]} >> $triggerdir/$node.subscribe_series.sql 2> $SMworkDir/slony1_dump.$node.log &
-
-#-------------------------------------------------------------------------
 # Adding the new entry to the slon log parser config file
 #-------------------------------------------------------------------------
-newtablefile=$tables_dir/$node.new.lst
-echo "$subscribers_dir/$node.new        $newtablefile" >> $parser_config
-logwrite "Adding the new entry to $parser_config"
-logwrite "[$subscribers_dir/$node.new   $newtablefile]" nl
+###########################
+## Lock the parser (will be unlocked in sdo_slony1_dump.sh)
+###########################
+if ( set -o noclobber; echo "$$" > "$subscribelockpath") 2> /dev/null;
+then
+    trap 'rm -f "$subscribelockpath"; exit 1' INT TERM HUP
+
+    newtablefile=$tables_dir/$node.new.lst
+    echo "$subscribers_dir/$node.new        $newtablefile" >> $parser_config
+    logwrite "Adding the new entry to $parser_config"
+    logwrite "[$subscribers_dir/$node.new   $newtablefile]" nl
+
+#-------------------------------------------------------------------------
+# Execute sdo_slony1_dump.sh
+#-------------------------------------------------------------------------
+    logwrite "Executing: [. $kRepDir/subscribe_manage/sdo_slony1_dump.sh $SLAVEDBNAME jsoc $SLAVEPORT $new_site_bool \"$SMworkDir/slon_counter.$node.txt\" ${schema_table[@]} >> $triggerdir/$node.subscribe_series.sql 2> $SMworkDir/slony1_dump.$node.log"
+    . $kRepDir/subscribe_manage/sdo_slony1_dump.sh $SLAVEDBNAME jsoc $SLAVEPORT $new_site_bool "$SMworkDir/slon_counter.$node.txt" ${schema_table[@]} >> $triggerdir/$node.subscribe_series.sql 2> $SMworkDir/slony1_dump.$node.log
+
+    if [ -e "$subscribelockpath" ] 
+    then
+        logwrite "ERROR: Unable to remove subscribe lock file $subscribelockpath"
+        exit 1
+    fi
+
+    trap - INT TERM HUP
+else
+    logwrite "Could not acquire the subscription lock [sql_gen]"
+    logwrite "Exiting"
+    exit 1
+fi
 
 #-------------------------------------------------------------------------
 # Checking the status of slony1 dump
 #-------------------------------------------------------------------------
 logwrite "Checking [$triggerdir/$node.subscribe_series.sql for the [-- dump complete] flag"
 unset check
-counter=0
-while [[ 1 == 1 ]]
-do
-        check=`tail -5 $triggerdir/$node.subscribe_series.sql | grep "\-\- dump complete"`
-        if [[ -n $check ]]
-        then
-                logwrite "Dump complete"
-		echo "COMMIT;" >> $triggerdir/$node.subscribe_series.sql
-                break
-        else
-                logwrite "Dump not yet complete."
-        fi
+check=`tail -5 $triggerdir/$node.subscribe_series.sql | grep "\-\- dump complete"`
+#if dump complete doesn't exists then it means it failed.
+if [ -n "$check" ]
+then
+  logwrite "Dump complete"
+  echo "COMMIT;" >> $triggerdir/$node.subscribe_series.sql
+else
+  logwrite "ERROR: There was an error found from sdo_slony1_dump.sh!"
+  logwrite "Review [$SMworkDir/slony1_dump.$node.log]"
+  logwrite "Error is [$check]"
+  logwrite "Exiting"
+  rm -f $input_file
+  exit 1
+fi
 
-        error_check=`grep -i "error" $SMworkDir/slony1_dump.$node.log`
-        if [[ -n $error_check ]]
-        then
-                logwrite "ERROR: There was an error found from sdo_slony1_dump.sh!"
-		logwrite "Review [$tempdir/slony1_dump.$node.log]"
-                logwrite "Error is [$error_check]"
-                logwrite "Exiting"
-		rm -f $node.subscribe_series.subupdate
-		exit
-        fi
-
-        if [[ $counter -lt $sl_dump_timeout ]]
-        then
-                counter=$(($counter+1))
-        else
-                logwrite "ERROR: Max number of tries reached, exiting"
-		rm -f $node.subscribe_series.subupdate
-                exit
-        fi
-	unset check error_check
-	sleep 1
-done
-
-rm -f $tempdir/slony1_dump.$node.log
+rm -f $SMworkDir/slony1_dump.$node.log
 
 #-------------------------------------------------------------------------
 # End of check for new subscriptions
@@ -335,7 +300,7 @@ do
     counter=$(( $counter + 1 ))
 done
 
-logwrite "Executing: tar -C $triggerdir/ -czvf $triggerdir/$node.sql.tar.gz $filelist" nl
+logwrite "Executing: tar -C $triggerdir/ -czvf $triggerdir/$node.sql.tar.gz $filelist"
 
 # Don't put $filelist in dquotes! tar needs the file names separate
 tar -C "$triggerdir/" -czvf "$triggerdir/$node.sql.tar.gz" $filelist
@@ -346,8 +311,8 @@ rm -f "$triggerdir/$node."*".createns.sql" "$triggerdir/$node.subscribe_series.s
 #-------------------------------------------------------------------------
 # Renaming the subupdate file to sqldone file in trigger directory for subscriber to find
 #-------------------------------------------------------------------------
-logwrite "Renaming sqlgen file $node.subscribe_series.subupdate to $triggerdir/$node.subscribe_series.sqldone" nl
+logwrite "Renaming sqlgen file $input_file to $triggerdir/$node.subscribe_series.sqldone" nl
 
-mv -f $node.subscribe_series.subupdate $triggerdir/$node.subscribe_series.sqldone
+mv -f $input_file $triggerdir/$node.subscribe_series.sqldone
 
 logwrite "Finished running $0"
diff --git a/base/drms/replication/subscribe_manage/subscription_cleanup b/base/drms/replication/subscribe_manage/subscription_cleanup
--- a/base/drms/replication/subscribe_manage/subscription_cleanup
+++ b/base/drms/replication/subscribe_manage/subscription_cleanup
@@ -4,29 +4,28 @@ pidfile=$0.pid
 #-------------------------------------------------------------------------
 # syntax check
 #-------------------------------------------------------------------------
-if [ $# -eq 5 ]
+if [ $# -eq 6 ]
 then
         config_file=$1
 	node=$2
 	new_site=$3
 	success=$4
 	input_file=$5
+        subscribelockpath=$6
 else
-	error="ERROR: Usage: $0 <server configuration file> <node> <new_site> <success of sql application, true/false> <subscription information file>"
+	error="ERROR: [$#] [$@] Usage: $0 <server configuration file> <node> <new_site> <success of sql application, true/false> <subscription information file> <path to subscription path>"
 	echo $error
-	exit
+	exit 1
 fi
+
 
 . $config_file
+. $kRepDir/subscribe_manage/subscribe_functions
 
-scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
-
-if [ -z "$kSMlogDir" ]
-then
-  logfile=../log/$scrbase.log
-else
-  logfile="$kSMlogDir/$scrbase.log"
-fi
+#--------------------------------------------------------------------
+# Setting up the log
+#--------------------------------------------------------------------
+logfile=$kSMlogDir/cleanup.$node.log
 
 if [ -z "$kMaxLog" ]
 then
@@ -57,18 +56,7 @@ else
   fi
 fi
 
-
-#--------------------------------------------------------------------
-# Setting up the log
-#--------------------------------------------------------------------
-
-logwrite () {
-        echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
-        if [ ! $2 == "" ]
-        then
-                echo `date +"%m-%d-%Y %H:%M:%S - "` >> $logfile
-        fi
-}
+exec >> $logfile 2>&1;
 
 logwrite "Starting $0 $1" nl
 
@@ -98,64 +86,120 @@ exec < $input_file
 			
         done
 
+## lock parser
+if ( set -o noclobber; echo "$$" > "$subscribelockpath") 2> /dev/null;
+then
+    trap 'rm -f "$subscribelockpath"; exit 1' INT TERM HUP
+
+    # Critical region
 #-------------------------------------------------------------------------
 # If successful, remove old directory and list file and replace with the new ones
 # If unsuccessful, remove new directory and list file
 #-------------------------------------------------------------------------
 # removing $node.new.lst from $parser_config
-logwrite "Removing new entry from $parser_config" 
-cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
-mv -f $parser_config.new $parser_config
+    logwrite "Removing new entry from $parser_config" 
+    cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
+    mv -f $parser_config.new $parser_config
 
-if [ $success == "true" ]
-then
+    if [ $success == "true" ]
+    then
+
 	if [ $new_site == "true" ]
 	then
 		# Success on new site!
-		logwrite "Subscriber SQL was a success"
-		logwrite "Adding the new entry to $parser_config "
-		logwrite "[$subscribers_dir/$node   $tables_dir/$node.lst]" nl
-		echo "$subscribers_dir/$node        $tables_dir/$node.lst" >> $parser_config
-		logwrite "Moving subscriber directory"
-		mv -f $subscribers_dir/$node.new $subscribers_dir/$node
-		logwrite "Moving subscriber table list"
-		mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+	    logwrite "Subscriber SQL was a success"
+	    logwrite "Adding the new entry to $parser_config "
+	    logwrite "[$subscribers_dir/$node   $tables_dir/$node.lst]" nl
+	    echo "$subscribers_dir/$node        $tables_dir/$node.lst" >> $parser_config
+	    logwrite "Moving subscriber directory"
+                ## remove any log files that might contain duplicates
+            if [ -f $SMworkDir/slon_counter.$node.txt ]
+            then
+                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
+
+                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+                while [ -f $slon_file ]
+                do
+                    rm -f $slon_file
+                    slon_counter=$(($slon_counter-1));
+                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+                done
+                rm -f $SMworkDir/slon_counter.$node.txt
+            else
+                logwrite "ERROR:: No $SMworkDir/slon_counter.$node.txt"
+            fi
+	    mv -f $subscribers_dir/$node.new $subscribers_dir/$node
+            
+	    logwrite "Moving subscriber table list"
+	    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
 	else
 		# Success on old site!
-		logwrite "Subscriber SQL was a success"
-		logwrite "Removing old subscriber directory"
-		rm -rf $subscribers_dir/$node
-		logwrite "Moving new directory the old file directory" nl
-		mv -f $subscribers_dir/$node.new $subscribers_dir/$node
-		logwrite "Removing old subscriber table list"
-		rm -f $tables_dir/$node.lst
-		logwrite "Moving new subscriber table list to old one"
-		mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+	    logwrite "Subscriber SQL was a success"
+	    logwrite "Moving new directory to the old file directory" nl
+                ## remove any log files that might contain duplicates
+            if [ -f $SMworkDir/slon_counter.$node.txt ]
+            then
+                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
+
+                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+                while [ -f $slon_file ]
+                do
+                    rm -f $slon_file
+                    slon_counter=$(($slon_counter-1));
+                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+                done
+                rm -f $SMworkDir/slon_counter.$node.txt
+            else
+                logwrite "ERROR:: No $SMworkDir/slon_counter.$node.txt"
+            fi
+	    cp -pr $subscribers_dir/$node.new/* $subscribers_dir/$node
+            rm -rf $subscribers_dir/$node.new
+	    logwrite "Removing old subscriber table list"
+	    rm -f $tables_dir/$node.lst
+	    logwrite "Moving new subscriber table list to old one"
+	    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
 	fi
-else
+
+    else
 	if [ $new_site == "true" ]
 	then
 		# Failure on new site!
-		logwrite "Subscriber SQL was not a success"
-		logwrite "Remove new subscriber folder" nl
-		rm -rf $subscribers_dir/$node.new
-		logwrite "Removing new subscriber table list"
-		rm -f $tables_dir/$node.new.lst
+	    logwrite "Subscriber SQL was not a success"
+	    logwrite "Remove new subscriber folder" nl
+	    rm -rf $subscribers_dir/$node.new
+	    logwrite "Removing new subscriber table list"
+	    rm -f $tables_dir/$node.new.lst
 	else
 		# Failure on old site!
-		logwrite "Subscriber SQL was not a success"
-		logwrite "Remove new subscriber folder" nl
-		rm -rf $subscribers_dir/$node.new
-		logwrite "Removing new subscriber table list"
-		rm -f $tables_dir/$node.new.lst
+	    logwrite "Subscriber SQL was not a success"
+	    logwrite "Remove new subscriber folder" nl
+	    rm -rf $subscribers_dir/$node.new
+	    logwrite "Removing new subscriber table list"
+	    rm -f $tables_dir/$node.new.lst
 	fi
+    fi
+
+    # release subscribe lock
+    rm -f "$subscribelockpath"
+
+    if [ -e "$subscribelockpath" ] 
+    then
+        logwrite "ERROR: Unable to remove subscribe lock file $subscribelockpath"
+        exit 1
+    fi
+
+    trap - INT TERM HUP
+else
+    logwrite "Could not acquire the subscription lock [cleanup]"
+    logwrite "Exiting"
+    exit 1
 fi
 
 #-------------------------------------------------------------------------
 # If successful, remove old directory and replace with the new one
 #-------------------------------------------------------------------------
 logwrite "Renaming the $node.subscribe_series.cleanup file to $node.subscribe_series.done" 
-mv $node.subscribe_series.cleanup $triggerdir/$node.subscribe_series.done
+mv $input_file $triggerdir/$node.subscribe_series.done
 logwrite "Removing the $node.subscribe_series.cfg file" nl
 rm -f $triggerdir/$node.subscribe_series.cfg
 logwrite "Removing the $node.subscribe_series.sqldone file" nl
diff --git a/base/drms/replication/subscribe_manage/subscription_manager b/base/drms/replication/subscribe_manage/subscription_manager
--- a/base/drms/replication/subscribe_manage/subscription_manager
+++ b/base/drms/replication/subscribe_manage/subscription_manager
@@ -1,43 +1,37 @@
 #!/bin/bash
-currDt=`date`
-pidfile=$0.pid
-diefile=$0.die
+#
+# Run this in the background as:
+#   subscription_manager /b/devtest/JSOC/proj/replication/etc/repserver.dev.cfg subscribelock.txt
+#--------------------------------------------------------------------
+# syntax check
+#--------------------------------------------------------------------
+if [ $# -eq 2 ]
+then
+        config_file=$1
+        subscribelock=$2
+else
+        error="ERROR: Usage: $0 <server configuration file> <subscription lock file>"
+        echo $error
+        exit 1;
+fi
+
+## First thing!: source config file
+. $config_file
 
 #--------------------------------------------------------------------
 # Setting up the log
 #--------------------------------------------------------------------
-
-logwrite () {
-        echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
-        if [ ! $2 == "" ]
-        then
-                echo `date +"%m-%d-%Y %H:%M:%S - "` >> $logfile
-        fi
-}
-
-#--------------------------------------------------------------------
-# syntax check
-#--------------------------------------------------------------------
-if [ $# -eq 1 ]
+if [ -z "$kSMlogDir" ] 
 then
-        config_file=$1
-else
-        error="ERROR: Usage: $0 <server configuration file>"
-        echo $error
-        exit
+  echo "There is not log directory [kSMlogDir] assigned in Config file!! Exiting ..."
+  exit 1;
+elif [ ! -d "$kSMlogDir" ]
+then
+  echo "Directory [kSMlogDir=$kSMlogDir] doesn't exists!! Exiting ..."
+  exit 1;
 fi
 
-# dot the config file
-. $config_file
-
-scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
-
-if [ -z "$kSMlogDir" ]
-then
-  logfile=../log/$scrbase.log
-else
-  logfile="$kSMlogDir/$scrbase.log"
-fi
+logfile=$kSMlogDir/subscription.log
 
 if [ -z "$kMaxLog" ]
 then
@@ -68,7 +62,21 @@ else
   fi
 fi
 
-logwrite "Starting $0" nl
+exec >> $logfile 2>&1
+
+#echo > $logfile
+
+## After setting the logfile variable source the subscriber functions
+## The ORDER things get sourced is IMPORTANT!!
+. $kRepDir/subscribe_manage/subscribe_functions
+
+currDt=`date`
+pidfile=$0.pid
+diefile=$0.die
+
+logwrite "Starting $0"
+
+logwrite "Using config file [$config_file]";
 
 trap "echo 'caught a signal'; rm -f $pidfile; exit" HUP INT TERM
 
@@ -91,23 +99,24 @@ echo $$ > $pidfile
 while [ 1 -eq 1 ]
 do
 
-if [ -f $diefile ]
-then
+  if [ -f $diefile ]
+  then
 	logwrite "Die file found, dying"
         rm -f $pidfile
         exit
-fi
+  fi
 
-#-------------------------------------------------------------------------
-# Reads the subscription request file into the arrays:
-# $series[] is the name of the series
-# $request[] is what type of request it is (subscribe or unsubscribe)
-#-------------------------------------------------------------------------
-# Find trigger files for sql_gen
-ls -1 $triggerdir | grep .subscribe_series.tgr > temp.txt
+  #-------------------------------------------------------------------------
+  # Reads the subscription request file into the arrays:
+  # $series[] is the name of the series
+  # $request[] is what type of request it is (subscribe or unsubscribe)
+  #-------------------------------------------------------------------------
+  # Find trigger files for sql_gen
+  logwrite "checking $triggerdir"
+  ls -1 $triggerdir | grep .subscribe_series.tgr > temp.txt
 
-counter=0
-exec < temp.txt
+  counter=0
+  exec < temp.txt
 	while read line
 	do
                 # skips blank lines
@@ -123,25 +132,34 @@ exec < temp.txt
 
 	done
 
-#-------------------------------------------------------------------------
-# For each trigger file found, extract the information and execute subscription_update
-#-------------------------------------------------------------------------
-counter=0
-while [ $counter -ne ${#triggerfile[*]} ]
-do
+  #-------------------------------------------------------------------------
+  # For each trigger file found, extract the information and execute subscription_update
+  #-------------------------------------------------------------------------
+  counter=0
+  while [ $counter -ne ${#triggerfile[*]} ]
+  do
 	logwrite "Extracting data from ${triggerfile[$counter]}" 
+
 	# Find the node name and new_site values and adds to new  file
-	subupdatefile=${triggerfile[$counter]/tgr/subupdate}
+	subupdatefile=$SMworkDir/${triggerfile[$counter]/tgr/subupdate.`date +'%Y%m%d.%H%M%S'`}
+
 	echo > $subupdatefile
+
 	exec < $triggerdir/${triggerfile[$counter]}
 		while read line
 		do
 			# skips blank lines
                		if [ ${#line} -eq 0 ]
-       		            then
-       		                 continue
+       		        then
+       		          continue
                		fi
-		
+	
+                        # skips comment lines
+                        if [ -z "${line%%#*}" ]
+                        then
+                          continue
+                        fi
+	
 			set - $line
 
 			if [ $1 == "node" ]
@@ -169,36 +187,30 @@ do
 			fi
 		done
 
-#-------------------------------------------------------------------------
-# Check to see if the subscriber is a new subscriber, or an old one.
-#-------------------------------------------------------------------------
+  #-------------------------------------------------------------------------
+  # Check to see if the subscriber is a new subscriber, or an old one.
+  #-------------------------------------------------------------------------
 	nodecheck=" "$node" "
 	new_site=true
-	logwrite "Checking for existing directory named $node"
+	logwrite "Checking for existing directory named $node in $subscribers_dir"
 	for i in `ls -1 $subscribers_dir`
 	do
-	compare=" "$i" "
-	logwrite "Comparing [$nodecheck] with [$compare]"
-	if [ ! "$nodecheck" == "$compare" ]
-	then
-		logwrite "Found no $node directory in $subscribers_dir"
-		#echo "new_site $new_site" >> $triggerdir/$node.subscribe_series.tgr
-	elif [ "$nodecheck" == "$compare" ]
-	then
-		logwrite "Found $node directory in $subscribers_dir, setting new_site to false"
-		new_site="false"
-		#echo "new_site $new_site" >> $triggerdir/$node.subscribe_series.tgr
-	fi
+          compare=" "$i" "
+          logwrite "Comparing [$nodecheck] with [$compare]"
+          if [ "$nodecheck" == "$compare" ]
+          then
+            logwrite "Found $node directory in $subscribers_dir, setting new_site to false"
+            new_site="false";
+            break;
+          fi
 	done
-	
+
 	logwrite "Appending [new_site $new_site] to $triggerdir/$node.subscribe_series.tgr"
 	echo "new_site $new_site" >> $triggerdir/$node.subscribe_series.tgr
 		
 	logwrite "Executing [$kRepDir/subscribe_manage/subscription_update $config_file $node $new_site $archive $retention $tapegroup $subupdatefile]" 
-		
-	# Executing [$kRepDir/subscribe_manage/subscription_update $config_file $node $new_site $archive $retention $tapegroup $subupdatefile &]
-	$kRepDir/subscribe_manage/subscription_update $config_file $node $new_site $archive $retention $tapegroup $subupdatefile &
-		
+	($kRepDir/subscribe_manage/subscription_update $config_file $node $new_site $archive $retention $tapegroup $subupdatefile $kServerLockDir/$subscribelock & )
+
 	# Renaming trigger file from $node.subscribe_series.tgr to $node.subscribe_series.cfg
 	logwrite "Move $triggerdir/${triggerfile[$counter]} $triggerdir/${triggerfile[$counter]/tgr/cfg}" nl
 	mv -f $triggerdir/${triggerfile[$counter]} $triggerdir/${triggerfile[$counter]/tgr/cfg}
@@ -209,23 +221,23 @@ do
 	#unset the node and new_site variables
 	unset node
 	unset new_site
-done		
+  done		
 
-# removes temp text file for finding the subscribe_series.tgr trigger files
-rm -f temp.txt
+  # removes temp text file for finding the subscribe_series.tgr trigger files
+  rm -f temp.txt
 
 
-#-------------------------------------------------------------------------
-# Looks for sqlapplied trigger files
-# Reads the sqlapplied files into the arrays:
-# $series[] is the name of the series
-# $request[] is what type of request it is (subscribe or unsubscribe)
-#-------------------------------------------------------------------------
-# Find trigger files for sql_gen
-ls -1 $triggerdir | grep .subscribe_series.sqlapplied > temp.txt
+  #-------------------------------------------------------------------------
+  # Looks for sqlapplied trigger files
+  # Reads the sqlapplied files into the arrays:
+  # $series[] is the name of the series
+  # $request[] is what type of request it is (subscribe or unsubscribe)
+  #-------------------------------------------------------------------------
+  # Find trigger files for sql_gen
+  ls -1 $triggerdir | grep .subscribe_series.sqlapplied > temp.txt
 
-counter=0
-exec < temp.txt
+  counter=0
+  exec < temp.txt
 	while read line
 	do
                 # skips blank lines
@@ -244,15 +256,16 @@ exec < temp.txt
 
 	done
 
-#-------------------------------------------------------------------------
-# For each sqlapplied file found, extract the information and execute subscription_update
-#-------------------------------------------------------------------------
-counter=0
-while [ $counter -ne ${#sqlappliedfile[*]} ]
-do
+  #-------------------------------------------------------------------------
+  # For each sqlapplied file found, extract the information and execute subscription_cleanup
+  #-------------------------------------------------------------------------
+  counter=0
+  while [ $counter -ne ${#sqlappliedfile[*]} ]
+  do
 	logwrite "Extracting data from ${sqlappliedfile[$counter]}"
 	# Finds the node name and new_site values and adds to new sqlgen file
-	appliedfile=${sqlappliedfile[$counter]/sqlapplied/cleanup}
+	appliedfile=$SMworkDir/${sqlappliedfile[$counter]/sqlapplied/cleanup}
+	logwrite "creating ${appliedfile}"
 	echo > $appliedfile
 	exec < $triggerdir/${sqlappliedfile[$counter]}		
 		while read line
@@ -283,14 +296,14 @@ do
 			fi
 		done
 
-	logwrite "Executing $kRepDir/subscribe_manage/subscription_cleanup $config_file $node $new_site $success $appliedfile &" 
-	logwrite "NOTE: Syntax: $kRepDir/subscribe_manage/subscription_cleanup <server configuration file> <node> <new subscription, true/false> <successful sql applictation true/false> <the sqlgen file with subscription info> &" nl
+        if [ -n "$success" ]
+        then
+          logwrite "Executing $kRepDir/subscribe_manage/subscription_cleanup $config_file $node $new_site $success $appliedfile &" 
 
-        # Must wrap this call to subscription_cleanup inside a drms_flock.pl call to prevent a race condition
-        # with prep_slon_logs.  The lockfile is serieslist.txt.
-
-	# Executing [$kRepDir/subscribe_manage/subscription_cleanup $config_file $node $new_site $success $appliedfile &]
-	$kRepDir/subscribe_manage/subscription_cleanup $config_file $node $new_site $success $appliedfile &
+          ($kRepDir/subscribe_manage/subscription_cleanup $config_file $node $new_site $success $appliedfile $kServerLockDir/$subscribelock & )
+        else
+          logwrite "ERROR:: FILE [$triggerdir/${sqlappliedfile[$counter]}] doesn't have a valid [Success is true/false] line" 
+        fi
 
 	logwrite "Removing $triggerdir/${sqlappliedfile[$counter]}" nl
 	rm -f $triggerdir/${sqlappliedfile[$counter]}
@@ -302,24 +315,24 @@ do
 	unset node
 	unset success
 	unset new_site
-done		
+  done		
 
-# removes temp text file for finding the subscribe_series.tgr trigger files
-rm -f temp.txt
+  # removes temp text file for finding the subscribe_series.tgr trigger files
+  rm -f temp.txt
 
 
-if [ -f $diefile ]
-then
+  if [ -f $diefile ]
+  then
 	logwrite "Die file found, dying" 
         rm -f $pidfile
         exit
-fi
+  fi
 
-sleep 10
+  sleep 10
 
-# removes values from triggerfile array.
-unset triggerfile
-unset sqlappliedfile
+  # removes values from triggerfile array.
+  unset triggerfile
+  unset sqlappliedfile
 
 done
 
diff --git a/base/drms/replication/subscribe_manage/subscription_update b/base/drms/replication/subscribe_manage/subscription_update
--- a/base/drms/replication/subscribe_manage/subscription_update
+++ b/base/drms/replication/subscribe_manage/subscription_update
@@ -9,7 +9,7 @@ pidfile=$0.pid
 #-------------------------------------------------------------------------
 # syntax check
 #-------------------------------------------------------------------------
-if [ $# -eq 7 ]
+if [ $# -eq 8 ]
 then
         config_file=$1
 	node=$2
@@ -18,27 +18,31 @@ then
 	retention=$5
 	tapegroup=$6
 	input_file=$7
+        subscribelockpath=$8
 else
-        error="ERROR: Usage: $0 <server configuration file> <node> <new subscription, true/false> <subscription information file>"
+        error="ERROR: Usage: $0 <server configuration file> <node> <new subscription, true/false> <subscription information file> <subscription lock file path>"
         echo $error
 	exit
 fi
 
+## First thing!: source config file
 . $config_file
-usertables=$tables_dir/$node.lst
 
-scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
-
-if [ -z "$kSMlogDir" ]
+if [ -z "$kSMlogDir" ] 
 then
-  logfile=../log/$scrbase.log
-else
-  logfile="$kSMlogDir/$scrbase.log"
+  echo "There is not log directory [kSMlogDir] assigned in Config file!! Exiting ..."
+  exit 1;
+elif [ ! -d "$kSMlogDir" ]
+then
+  echo "Directory [kSMlogDir=$kSMlogDir] doesn't exists!! Exiting ..."
+  exit 1;
 fi
 
+logfile=$kSMlogDir/update.$node.log
+
 if [ -z "$kMaxLog" ]
-then
-  maxlog=1048576
+ then
+   maxlog=1048576
 else
   maxlog="$kMaxLog"
 fi
@@ -65,26 +69,79 @@ else
   fi
 fi
 
-#--------------------------------------------------------------------
-# Setting up the log
-#--------------------------------------------------------------------
+exec >> $logfile 2>&1
 
-logwrite () {
-        echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
-        if [ ! $2 == "" ]
-        then
-                echo `date +"%m-%d-%Y %H:%M:%S - "` >> $logfile
-        fi
-}
+## After setting the logfile variable source the subscriber functions
+## The ORDER things get sourced is IMPORTANT!!
+. $kRepDir/subscribe_manage/subscribe_functions
+
+usertables=$tables_dir/$node.lst
+
 
 logwrite "Starting $0 $1" nl
+
+## At this point I'd like to test if this is a subscription retry,
+## e.g. the client connection dropped and it retried again
+## or if it is a legit one, a first try.
+last_running_subupdate=`ls -1r ${input_file%.[0-9]*.[0-9]*}* | grep -v $input_file | tail -1`;
+
+## Note if last_running_subupdate is empty then this is NOT a retry
+if [ -n "$last_running_subupdate" ]
+then
+  ## we've got a retry
+  ##
+  grep_pid=`grep "#UPDATE PID:" $last_running_subupdate`; 
+  update_pid=${grep_pid#"#UPDATE PID:"};
+  program_name="";
+  ## check if pid is running
+  if [ -n $update_pid ]
+  then
+    program_name=`ps -p $update_pid -o comm=`;
+  fi
+
+  this_basename=`basename $0`;
+  if [ -n "$program_name" ] && [ "$program_name" == "$this_basename" ]
+  then
+    ## ok program is already running
+    logwrite "There is a [$this_basename] with pid [$update_pid] already running on node [$node] ... exiting"
+    ## exit
+    rm -f $input_file;
+    ## TODO inform the client this is the case.
+    exit 1;
+  else
+    ## no pid running
+    logwrite "Accepting request as previous instance of $this_basename died";
+    logwrite "cleaning old [$last_running_subupdate] file";
+    rm -f $last_running_subupdate;
+    ## do some cleaning?? and continue
+  fi
+
+  ## making sure I don't break anything down the line
+  unset last_running_subupdate
+  unset grep_pid
+  unset update_pid
+  unset program_name
+  unset this_basename
+
+fi
+
+## accept this request!
+echo "#UPDATE PID:$$" >> $input_file;
 
 #-------------------------------------------------------------------------
 # Reads the subscription request file into the arrays:
 # $series[] is the name of the series
 # $request[] is what type of request it is (subscribe or unsubscribe)
 #-------------------------------------------------------------------------
+# Note: the input_file is a copy of the trigger file the client originally sent but with the "tgr" extension replaced by subupdate. e.g. NSO.subscribe_series.subupdate
+## 
+## see that input file now contains the PID of the process dealing with it
+## i.e. #UPDATE PID:<pid>
+## basically we are allowing comment lines in the file
+##
 counter=0
+# $input_file is the subupdate file - a list of series and the action to take on that series
+# (subscribe/unsubscribe)
 exec < $input_file
         while read line
         do
@@ -93,7 +150,13 @@ exec < $input_file
                 then
 			continue
                 fi
+                # skips comment lines
+                if [ -z "${line%%#*}" ]
+                then
+			continue
+                fi
 		set - $line
+logwrite "series [$1] and request [$2]";
                 series[$counter]=$1
 		request[$counter]=$2
 
@@ -110,15 +173,20 @@ then
 	mkdir $subscribers_dir/$node.new
 	chmod a+rx $subscribers_dir/$node.new
 else
-	logwrite "Old site, copying directory $subscribers_dir/$node to $subscribers_dir/$node.new"
-	cp -far  $subscribers_dir/$node $subscribers_dir/$node.new
+	logwrite "Old site, making directory $subscribers_dir/$node.new"
+	mkdir $subscribers_dir/$node.new
+	chmod a+rx $subscribers_dir/$node.new
+## We don't need the copy anymore
+##	cp -far  $subscribers_dir/$node $subscribers_dir/$node.new
 fi
 newtablefile=$tables_dir/$node.new.lst
+logwrite "newtablefile is [$newtablefile]"
 echo > $newtablefile
 
 #-------------------------------------------------------------------------
 # Applies the subscription information to the usertables file
 #-------------------------------------------------------------------------
+newsubscription=0
 # If new_site is true, adds all subscriptions in the config file to the end of the new usertables file
 if [ $new_site == "true" ]
 then
@@ -129,7 +197,14 @@ then
 	do
 		logwrite "Adding [${series[$counter]} to $newtablefile"
 		echo "${series[$counter]}" >> $newtablefile
-		
+
+                # ART - this was missing
+                newsubscription=1
+                
+                # ART - this assumes that there are no unsubscribe requests
+                # in the client's trigger file, if the client is a new
+                # subscriber (should filter out these bad unsubscribe
+                # requests, or fail or something)
 		counter=$(( $counter + 1 ))
 	done
 	logwrite " "
@@ -139,9 +214,11 @@ then
 # Second, adds all subscriptions with the tag "subscribe" to the end of the file
 elif [ $new_site == "false" ]
 then
+    unsubhappening=0
 	logwrite "The Subscription request is from a current site"
 
 	# Removes subscriptions if $request[#] is "unsubscribe"
+        # usertables is the subscribing node's .lst file
 	exec < $usertables
         	while read line
         	do
@@ -154,20 +231,35 @@ then
                 	        continue
 			fi
 
+                        # skips comment lines
+                        if [ -z "${line%%#*}" ]
+                        then
+                          continue
+                        fi
 			# Loops through each entry in the $series array and $request array for each $line
 			while [ $counter -lt ${#series[*]} ]
 			do
 				linecompare="${series[$counter]}"
+logwrite "counter [$counter] [${#series[*]}] request counter [${request[$counter]}] and line [$line] and linecompare [$linecompare]"
 				if [[ "$line" == "$linecompare" && ${request[$counter]} == "unsubscribe" ]]
 				then
-					# Found match, setting $flag to 1 so line doesn't get rewritten to tablelist
-					flag=1
+				    # Found match, setting $flag to 1 so line doesn't get rewritten to tablelist
+                                    # flag == 1 means an unsubscribe request for an existing series
+                                    # (applicable only for existing sites)
+                                    # ART - flag can be unset in later iterations, which is okay for
+                                    # this double loop, but flag is used at the end of this script. 
+                                    # That location is testing for ANY unsubscribe, so we need a 
+                                    # new variable
+				    flag=1
+                                    unsubhappening=1
 				fi
 				
 				counter=$(( $counter + 1 ))
 			done
 
 			# if a match was not found, write the line to the new user tables file
+                        # if not requesting an unsubscribe to the current series in the .lst file
+                        # write the .lst file line to the newtablefile (node.lst.new)
 			if [ $flag -eq 0 ]
 			then
 				logwrite "Writing $line to $newtablefile"
@@ -187,17 +279,17 @@ then
 			logwrite "Checking to see if subscription request already exists"
 			logwrite "Executing [check=cat $newtablefile | grep ${series[$counter]}]"
 			check=`cat $newtablefile | grep "${series[$counter]}"`
-			logwrite "Check is [$check]"
 			if [ "$check" == "" ]
 			then
 				logwrite "Subscription does not already exist"
 				logwrite "Writing ${series[$counter]} to $newtablefile"
 				echo "${series[$counter]}" >> $newtablefile
+                                newsubscription=1
 			else 
 				logwrite "The subscription request [${series[$counter]}] already exists"
 				logwrite "Removing the subscription request [${series[$counter]}] from [$input_file]"
-				cat $input_file | grep -v "${series[$counter]}" > newinputfile
-				mv -f newinputfile $input_file
+				cat $input_file | grep -v "${series[$counter]}" > $SMworkDir/newinputfile
+				mv -f $SMworkDir/newinputfile $input_file
 			fi
 			unset check
 		fi	
@@ -217,11 +309,23 @@ fi
 #logwrite "[$subscribers_dir/$node.new	$newtablefile]" nl
 #	
 #echo "$subscribers_dir/$node.new	$newtablefile" >> $parser_config
+if [ $newsubscription -eq 1 ]
+then
+  #-------------------------------------------------------------------------
+  # Execute the sql_gen script [$kRepDir/subscribe_manage/sql_gen $node $new_site $input_file]"
+  #-------------------------------------------------------------------------
+  logwrite "Executing the sql_gen script [. $kRepDir/subscribe_manage/sql_gen $node $new_site $input_file]" nl
+  . $kRepDir/subscribe_manage/sql_gen $node $new_site $archive $retention $tapegroup $input_file
+# ART - the $new_site == "false" was missing, and replace flag with unsubhappening - 
+# flag wasn't the right variable to use
+elif [ $new_site == "false" -a $unsubhappening -eq 1 ]
+then
+    # There were no new subscriptions, and at least one unsubscribe, so we need to
+    # overwrite the old .lst file - the new one will be missing at least one series
+    mv -f  $newtablefile $usertables
+    rm -fr $subscribers_dir/$node.new
+fi
 
-#-------------------------------------------------------------------------
-# Execute the sql_gen script [$kRepDir/subscribe_manage/sql_gen $node $new_site $input_file]"
-#-------------------------------------------------------------------------
-logwrite "Executing the sql_gen script [$kRepDir/subscribe_manage/sql_gen $config_file $node $new_site $input_file]" nl
-$kRepDir/subscribe_manage/sql_gen $config_file $node $new_site $archive $retention $tapegroup $input_file &
+logwrite "Removing input file [$input_file]"
+rm -f "$input_file"
 logwrite "$0 finished"
-
diff --git a/base/drms/replication/subscribe_series/subscribe_series b/base/drms/replication/subscribe_series/subscribe_series
--- a/base/drms/replication/subscribe_series/subscribe_series
+++ b/base/drms/replication/subscribe_series/subscribe_series
@@ -2,6 +2,9 @@
 #export SSH_AUTH_SOCK=/tmp/ssh-HgUgDH2809/agent.2809
 #export SSH_AGENT_PID=2810
 
+# Run as:
+#   /home/production/devtest/cvstree/base/drms/replication/subscribe_series/subscribe_series /home/production/devtest/cvstree/proj/replication/etc/repclient.shoom.cfg subscribe_list.cfg /home/production/.ssh-agent_rs
+
 function RM {
 
   cmd="/bin/rm";
@@ -453,70 +456,6 @@ logwrite "Starting $0 from $scriptdir" nl
 # Make this relative to working dir
 statefile=$kLocalWorkingDir/ssstate.txt
 
-# extract seriesname from the $subscribe_file file
-# XXX - ART
-# Create an array of series - the createns check must be on a per-series basis.
-# We only care about series being subscribed to (and not being dropped from subscription)
-subserieslst=`cat $subscribe_file | egrep '^[^#[:space:]]' | grep -vi unsubscribe | awk '{print $1}'`
-unsubserieslst=`cat $subscribe_file | egrep '^[^#[:space:]]' | grep -i unsubscribe | awk '{print $1}'`
-
-logwrite "Series being subscribed to:"
-
-ctr=0
-while [ 1 -eq 1 ]
-do
-    index=$(( $ctr + 1 ))
-    awkscr='{print $'"$index"'}'
-    str=`echo $subserieslst | awk "$awkscr"`
-    if [ -z "$str" ]
-    then
-        break
-    fi
-    subseries[$ctr]=$str
-    logwrite "$str ($ctr)"
-    ctr=$(( $ctr + 1 ))
-done
-
-logwrite "Series being dropped from subscription:"
-ctr=0
-while [ 1 -eq 1 ]
-do
-    index=$(( $ctr + 1 ))
-    awkscr='{print $'"$index"'}'
-    str=`echo $unsubserieslst | awk "$awkscr"`
-    if [ -z "$str" ]
-    then
-        break
-    fi
-    unsubseries[$ctr]=$str
-    logwrite "$str ($ctr)"
-    ctr=$(( $ctr + 1 ))
-done
-
-# extract action from subscribe_list.cfg (if at least one action is unsubscribe, then we need to 
-# force get_slony_logs.pl after the die file has been removed)
-
-if [ ${#unsubseries[@]} -gt 0 ]
-then
-    unsubscribe=1
-else
-    unsubscribe=0
-fi
-
-if [ -z "$kSQLIngestionProgram" ]
-then
-  ingestprog=get_slony_logs.pl
-else
-  ingestprog="$kSQLIngestionProgram"
-fi
-
-if [ -z "$kDeleteSeriesProgram" ]
-then
-  delseriesprog=delete_series
-else
-  delseriesprog="$kDeleteSeriesProgram"
-fi
-
 #--------------------------------------------------------------------
 # Set up ssh keys
 #--------------------------------------------------------------------
@@ -558,6 +497,89 @@ if [ -z $SSH_AGENT_PID ]
 then
     echo "Couldn't find ssh-agent.\n"
     exit 1
+fi
+
+if [ -z "$kSQLIngestionProgram" ]
+then
+  ingestprog=get_slony_logs.pl
+else
+  ingestprog="$kSQLIngestionProgram"
+fi
+
+if [ -z "$kDeleteSeriesProgram" ]
+then
+  delseriesprog=delete_series
+else
+  delseriesprog="$kDeleteSeriesProgram"
+fi
+
+# Check for a log reprocessing request
+reproreq=`cat $subscribe_file | egrep '^[^#[:space:]]' | grep -wi repro`
+
+if [ ! -z $reproreq ] 
+then
+    # Do a log-reprocessing request - call a perl script (easier for me)
+    SetState "repro"
+    "$kRepDir/subscribe_series/req.pl" "$subscribe_file" "$logfile" "$kLocalWorkingDir"
+    # clean up log file (in case it got really big for some reason when reqrepro.pl was called
+    if [ $? -ne 0 ] 
+    then
+        logecho "Couldn't process log-re-parsing request."
+        exit 1;
+    else
+        logwrite "Re-parsing request issued."
+        SetState "end"
+    fi
+else
+# extract seriesname from the $subscribe_file file
+# XXX - ART
+# Create an array of series - the createns check must be on a per-series basis.
+# We only care about series being subscribed to (and not being dropped from subscription)
+    subserieslst=`cat $subscribe_file | egrep '^[^#[:space:]]' | grep -wi subscribe | awk '{print $1}'`
+    unsubserieslst=`cat $subscribe_file | egrep '^[^#[:space:]]' | grep -i unsubscribe | awk '{print $1}'`
+
+    logwrite "Series being subscribed to:"
+
+    ctr=0
+    while [ 1 -eq 1 ]
+    do
+        index=$(( $ctr + 1 ))
+        awkscr='{print $'"$index"'}'
+        str=`echo $subserieslst | awk "$awkscr"`
+        if [ -z "$str" ]
+        then
+            break
+        fi
+        subseries[$ctr]=$str
+        logwrite "$str ($ctr)"
+        ctr=$(( $ctr + 1 ))
+    done
+
+    logwrite "Series being dropped from subscription:"
+    ctr=0
+    while [ 1 -eq 1 ]
+    do
+        index=$(( $ctr + 1 ))
+        awkscr='{print $'"$index"'}'
+        str=`echo $unsubserieslst | awk "$awkscr"`
+        if [ -z "$str" ]
+        then
+            break
+        fi
+        unsubseries[$ctr]=$str
+        logwrite "$str ($ctr)"
+        ctr=$(( $ctr + 1 ))
+    done
+
+# extract action from subscribe_list.cfg (if at least one action is unsubscribe, then we need to 
+# force get_slony_logs.pl after the die file has been removed)
+
+    if [ ${#unsubseries[@]} -gt 0 ]
+    then
+        unsubscribe=1
+    else
+        unsubscribe=0
+    fi
 fi
 
 #--------------------------------------------------------------------
@@ -652,9 +674,6 @@ then
 fi
 
 
-
-
-
 #--------------------------------------------------------------------
 # Stopping ingestion script and copy trigger file to Manager
 #--------------------------------------------------------------------
@@ -677,6 +696,10 @@ then
 # it. The client (this script) should lock the file, then 
 # scp it, then chgrp/chmod it (this script should do the
 # chgrp/chmod).
+#
+# Even easier - just add a "__EOF__" line to the end of the trigger
+# file - the server ignores the file, unless it sees this __EOF__
+# string
     chmod g+w "$triggerfile"
     SCP -p "$triggerfile" "$kRSUser@$kRSServer:$kRSTriggerDir/."
 
