My first attempt at making the subscribe_manage scripts non hard-coded; but they still dont work

diff --git a/base/drms/replication/subscribe_manage/sql_gen b/base/drms/replication/subscribe_manage/sql_gen
--- a/base/drms/replication/subscribe_manage/sql_gen
+++ b/base/drms/replication/subscribe_manage/sql_gen
@@ -32,12 +32,49 @@ fi
 
 . "$config_file"
 
-logfile=../log/$0.$node.log
+scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
+
+if [ -z "$kSMlogDir" ]
+then
+  logfile=../log/$scrbase.log
+else
+  logfile="$kSMlogDir/$scrbase.log"
+fi
+
+if [ -z "$kMaxLog" ]
+then
+  maxlog=1048576
+else
+  maxlog="$kMaxLog"
+fi
+
+if [ ! -f "$logfile" ]
+then
+  touch "$logfile"
+  if [ $? -ne 0 ]
+  then
+    logecho "Couldn't touch log file [$logfile] ... exiting."
+    exit 1;
+  fi
+else
+  # log exists, truncate if getting too big
+  sz=`stat -c%s $logfile`
+  if [ $sz -ge $maxlog ]
+  then
+    : > "$logfile"
+    if [ $? -ne 0 ]
+      then
+        logecho "Couldn't truncate log file [$logfile] ... exiting."
+      exit 1;
+    fi
+  fi
+fi
+
 
 #--------------------------------------------------------------------
 # Setting up the log
 #--------------------------------------------------------------------
-echo > $logfile
+
 logwrite () {
         echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
         if [ ! $2 == "" ]
@@ -188,9 +225,9 @@ do
 	if [ "$check" == "" ]
 	then
 		# If first time finding this schema, execute ./createns
-		logwrite "Executing [./createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER >> $triggerdir/$node.${schema[$counter]}.createns.sql]"
+		logwrite "Executing [$kModDir/createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER >> $triggerdir/$node.${schema[$counter]}.createns.sql]"
 		#echo "Createns >>" #remove
-		./createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER > $triggerdir/$node.${schema[$counter]}.createns.sql
+		$kModDir/createns ns=${schema[$counter]} nsgroup=user dbusr=$REPUSER > $triggerdir/$node.${schema[$counter]}.createns.sql
 		#echo "<<Createns" #remove
 		# echo ${schema[$counter]} >> $triggerdir/$node.createns.sql
 	fi
@@ -211,8 +248,8 @@ do
 	if [ "$check" == "" ]
 	then
 		# If first time finding this schema_table, execute ./createtabstruct
-		logwrite "Executing [./createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql]"
-		./createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql
+		logwrite "Executing [$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql]"
+		$kModDir/createtabstructure in=${schema_table[$counter]} out=${schema_table[$counter]} archive=$archive retention=$retention tapegroup=$tapegroup owner=slony >> $triggerdir/$node.subscribe_series.sql
 	fi
 	counter=$(( $counter + 1 ))
 done
diff --git a/base/drms/replication/subscribe_manage/subscription_cleanup b/base/drms/replication/subscribe_manage/subscription_cleanup
--- a/base/drms/replication/subscribe_manage/subscription_cleanup
+++ b/base/drms/replication/subscribe_manage/subscription_cleanup
@@ -19,12 +19,49 @@ fi
 
 . $config_file
 
-logfile=../log/$0.$node.log
+scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
+
+if [ -z "$kSMlogDir" ]
+then
+  logfile=../log/$scrbase.log
+else
+  logfile="$kSMlogDir/$scrbase.log"
+fi
+
+if [ -z "$kMaxLog" ]
+then
+  maxlog=1048576
+else
+  maxlog="$kMaxLog"
+fi
+
+if [ ! -f "$logfile" ]
+then
+  touch "$logfile"
+  if [ $? -ne 0 ]
+  then
+    logecho "Couldn't touch log file [$logfile] ... exiting."
+    exit 1;
+  fi
+else
+  # log exists, truncate if getting too big
+  sz=`stat -c%s $logfile`
+  if [ $sz -ge $maxlog ]
+  then
+    : > "$logfile"
+    if [ $? -ne 0 ]
+      then
+        logecho "Couldn't truncate log file [$logfile] ... exiting."
+      exit 1;
+    fi
+  fi
+fi
+
 
 #--------------------------------------------------------------------
 # Setting up the log
 #--------------------------------------------------------------------
-echo > $logfile
+
 logwrite () {
         echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
         if [ ! $2 == "" ]
diff --git a/base/drms/replication/subscribe_manage/subscription_manager b/base/drms/replication/subscribe_manage/subscription_manager
--- a/base/drms/replication/subscribe_manage/subscription_manager
+++ b/base/drms/replication/subscribe_manage/subscription_manager
@@ -1,13 +1,12 @@
 #!/bin/bash
 currDt=`date`
 pidfile=$0.pid
-logfile=../log/$0.log
 diefile=$0.die
 
 #--------------------------------------------------------------------
 # Setting up the log
 #--------------------------------------------------------------------
-echo > $logfile
+
 logwrite () {
         echo `date +"%m-%d-%Y %H:%M:%S - "` "$1" >> $logfile
         if [ ! $2 == "" ]
@@ -16,25 +15,58 @@ logwrite () {
         fi
 }
 
-logwrite "Starting $0" nl
-
 #--------------------------------------------------------------------
 # syntax check
 #--------------------------------------------------------------------
 if [ $# -eq 1 ]
 then
         config_file=$1
-        logwrite "Using $config_file" nl
 else
         error="ERROR: Usage: $0 <server configuration file>"
         echo $error
-        logwrite "$error"
         exit
 fi
 
 # dot the config file
 . $config_file
 
+scrbase=`perl -e 'if ($ARGV[0] =~ /.*\/([^\/]+)/) { print $1; } else { print $ARGV[0]; }' $0`
+
+if [ -z "$kSMlogDir" ]
+then
+  logfile=../log/$scrbase.log
+else
+  logfile="$kSMlogDir/$scrbase.log"
+fi
+
+if [ -z "$kMaxLog" ]
+then
+  maxlog=1048576
+else
+  maxlog="$kMaxLog"
+fi
+
+if [ ! -f "$logfile" ]
+then
+  touch "$logfile"
+  if [ $? -ne 0 ]
+  then
+    logecho "Couldn't touch log file [$logfile] ... exiting."
+    exit 1;
+  fi
+else
+  # log exists, truncate if getting too big
+  sz=`stat -c%s $logfile`
+  if [ $sz -ge $maxlog ]
+  then
+    : > "$logfile"
+    if [ $? -ne 0 ]
+      then
+        logecho "Couldn't truncate log file [$logfile] ... exiting."
+      exit 1;
+    fi
+  fi
+fi
 
 logwrite "Starting $0" nl
 
