Look in subscription_cleanup to obtain lock; add an arg to the config files

diff --git a/base/drms/replication/subscribe_manage/subscription_cleanup b/base/drms/replication/subscribe_manage/subscription_cleanup
--- a/base/drms/replication/subscribe_manage/subscription_cleanup
+++ b/base/drms/replication/subscribe_manage/subscription_cleanup
@@ -86,114 +86,138 @@ exec < $input_file
 			
         done
 
-## lock parser
-if ( set -o noclobber; echo "$$" > "$subscribelockpath") 2> /dev/null;
-then
-    trap 'rm -f "$subscribelockpath"; exit 1' INT TERM HUP
+cleanup_lockfile_success=0
+cleanup_counter=0
+while [[ 1 == 1 ]]; do
+cleanup_counter=$(( $cleanup_counter + 1 ))
 
-    # Critical region
-#-------------------------------------------------------------------------
-# If successful, remove old directory and list file and replace with the new ones
-# If unsuccessful, remove new directory and list file
-#-------------------------------------------------------------------------
-# removing $node.new.lst from $parser_config
-    logwrite "Removing new entry from $parser_config" 
-    cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
-    mv -f $parser_config.new $parser_config
-
-    if [ $success == "true" ]
-    then
-
-	if [ $new_site == "true" ]
+	## lock parser
+	if ( set -o noclobber; echo "$$" > "$subscribelockpath") 2> /dev/null;
 	then
-		# Success on new site!
-	    logwrite "Subscriber SQL was a success"
-	    logwrite "Adding the new entry to $parser_config "
-	    logwrite "[$subscribers_dir/$node   $tables_dir/$node.lst]" nl
-	    echo "$subscribers_dir/$node        $tables_dir/$node.lst" >> $parser_config
-	    logwrite "Moving subscriber directory"
-                ## remove any log files that might contain duplicates
-            if [ -f $SMworkDir/slon_counter.$node.txt ]
-            then
-                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
-
-                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
-                while [ -f $slon_file ]
-                do
-                    rm -f $slon_file
-                    slon_counter=$(($slon_counter-1));
-                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
-                done
-                rm -f $SMworkDir/slon_counter.$node.txt
-            else
-                logwrite "ERROR:: No $SMworkDir/slon_counter.$node.txt"
-            fi
-	    mv -f $subscribers_dir/$node.new $subscribers_dir/$node
-            
-	    logwrite "Moving subscriber table list"
-	    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+	    trap 'rm -f "$subscribelockpath"; exit 1' INT TERM HUP
+	    
+	    cleanup_lockfile_success=1
+	
+	
+	    # Critical region
+	#-------------------------------------------------------------------------
+	# If successful, remove old directory and list file and replace with the new ones
+	# If unsuccessful, remove new directory and list file
+	#-------------------------------------------------------------------------
+	# removing $node.new.lst from $parser_config
+	    logwrite "Removing new entry from $parser_config" 
+	    cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
+	    mv -f $parser_config.new $parser_config
+	
+	    if [ $success == "true" ]
+	    then
+	
+		if [ $new_site == "true" ]
+		then
+			# Success on new site!
+		    logwrite "Subscriber SQL was a success"
+		    logwrite "Adding the new entry to $parser_config "
+		    logwrite "[$subscribers_dir/$node   $tables_dir/$node.lst]" nl
+		    echo "$subscribers_dir/$node        $tables_dir/$node.lst" >> $parser_config
+		    logwrite "Moving subscriber directory"
+	                ## remove any log files that might contain duplicates
+	            if [ -f $SMworkDir/slon_counter.$node.txt ]
+	            then
+	                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
+	
+	                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+	                while [ -f $slon_file ]
+	                do
+	                    rm -f $slon_file
+	                    slon_counter=$(($slon_counter-1));
+	                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+	                done
+	                rm -f $SMworkDir/slon_counter.$node.txt
+	            else
+	                logwrite "ERROR:: No $SMworkDir/slon_counter.$node.txt"
+	            fi
+		    mv -f $subscribers_dir/$node.new $subscribers_dir/$node
+	            
+		    logwrite "Moving subscriber table list"
+		    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+		else
+			# Success on old site!
+		    logwrite "Subscriber SQL was a success"
+		    logwrite "Moving new directory to the old file directory" nl
+	                ## remove any log files that might contain duplicates
+	            if [ -f $SMworkDir/slon_counter.$node.txt ]
+	            then
+	                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
+	
+	                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+	                while [ -f $slon_file ]
+	                do
+	                    rm -f $slon_file
+	                    slon_counter=$(($slon_counter-1));
+	                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
+	                done
+	                rm -f $SMworkDir/slon_counter.$node.txt
+	            else
+	                logwrite "NOTE:: No $SMworkDir/slon_counter.$node.txt (only needed if adding series to subscription list)"
+	            fi
+		    cp -pr $subscribers_dir/$node.new/* $subscribers_dir/$node
+	            rm -rf $subscribers_dir/$node.new
+		    logwrite "Removing old subscriber table list"
+		    rm -f $tables_dir/$node.lst
+		    logwrite "Moving new subscriber table list to old one"
+		    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+		fi
+	
+	    else
+		if [ $new_site == "true" ]
+		then
+			# Failure on new site!
+		    logwrite "Subscriber SQL was not a success"
+		    logwrite "Remove new subscriber folder" nl
+		    rm -rf $subscribers_dir/$node.new
+		    logwrite "Removing new subscriber table list"
+		    rm -f $tables_dir/$node.new.lst
+		else
+			# Failure on old site!
+		    logwrite "Subscriber SQL was not a success"
+		    logwrite "Remove new subscriber folder" nl
+		    rm -rf $subscribers_dir/$node.new
+		    logwrite "Removing new subscriber table list"
+		    rm -f $tables_dir/$node.new.lst
+		fi
+	    fi
+	
+	    # release subscribe lock
+	    rm -f "$subscribelockpath"
+	
+	    if [ -e "$subscribelockpath" ] 
+	    then
+	        logwrite "ERROR: Unable to remove subscribe lock file $subscribelockpath"
+	        exit 1
+	    fi
+	
+	    trap - INT TERM HUP
 	else
-		# Success on old site!
-	    logwrite "Subscriber SQL was a success"
-	    logwrite "Moving new directory to the old file directory" nl
-                ## remove any log files that might contain duplicates
-            if [ -f $SMworkDir/slon_counter.$node.txt ]
-            then
-                slon_counter=`cat $SMworkDir/slon_counter.$node.txt`;
-
-                slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
-                while [ -f $slon_file ]
-                do
-                    rm -f $slon_file
-                    slon_counter=$(($slon_counter-1));
-                    slon_file=`printf "$subscribers_dir/$node.new/slony1_log_2_020%d.log" $slon_counter`;
-                done
-                rm -f $SMworkDir/slon_counter.$node.txt
-            else
-                logwrite "NOTE:: No $SMworkDir/slon_counter.$node.txt (only needed if adding series to subscription list)"
-            fi
-	    cp -pr $subscribers_dir/$node.new/* $subscribers_dir/$node
-            rm -rf $subscribers_dir/$node.new
-	    logwrite "Removing old subscriber table list"
-	    rm -f $tables_dir/$node.lst
-	    logwrite "Moving new subscriber table list to old one"
-	    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+	    logwrite "Could not acquire the subscription lock [cleanup]"
+	    logwrite "Sleeping for 1 second"
 	fi
 
-    else
-	if [ $new_site == "true" ]
+	if [[ $cleanup_lockfile_success -eq 1 ]]
 	then
-		# Failure on new site!
-	    logwrite "Subscriber SQL was not a success"
-	    logwrite "Remove new subscriber folder" nl
-	    rm -rf $subscribers_dir/$node.new
-	    logwrite "Removing new subscriber table list"
-	    rm -f $tables_dir/$node.new.lst
-	else
-		# Failure on old site!
-	    logwrite "Subscriber SQL was not a success"
-	    logwrite "Remove new subscriber folder" nl
-	    rm -rf $subscribers_dir/$node.new
-	    logwrite "Removing new subscriber table list"
-	    rm -f $tables_dir/$node.new.lst
+		logwrite "Flag found that signals establishing lock file was a success. Breaking from loop"
+		break
 	fi
-    fi
 
-    # release subscribe lock
-    rm -f "$subscribelockpath"
+	if [[ $cleanup_counter -eq $cleanup_max_tries ]]
+	then
+	        logwrite "Max tries [$cleanup_max_tries] reached, exiting!"
+	        exit
+	fi
 
-    if [ -e "$subscribelockpath" ] 
-    then
-        logwrite "ERROR: Unable to remove subscribe lock file $subscribelockpath"
-        exit 1
-    fi
+	sleep 1
+done
 
-    trap - INT TERM HUP
-else
-    logwrite "Could not acquire the subscription lock [cleanup]"
-    logwrite "Exiting"
-    exit 1
-fi
+
 
 #-------------------------------------------------------------------------
 # If successful, remove old directory and replace with the new one
