Complete the code needed to maintain the su_production.slonycfg and su_production.slonylst tables. When the slony_parser.cfg and .lst files get updated, we need to update these two database tables.

diff --git a/base/drms/replication/subscribe_manage/subscription_cleanup b/base/drms/replication/subscribe_manage/subscription_cleanup
--- a/base/drms/replication/subscribe_manage/subscription_cleanup
+++ b/base/drms/replication/subscribe_manage/subscription_cleanup
@@ -108,6 +108,10 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 	    logwrite "Removing new entry from $parser_config" 
 	    cat $parser_config | grep -v "$node.new.lst" > $parser_config.new
 	    mv -f $parser_config.new $parser_config
+
+        # ART LST - Remove $node.new from $parser_config and remove $node.new from su_production.slonycfg
+        # and remove all entries for $node.new from su_production.slonylst.
+        $kRepDir/subscribe_manage/gentables.pl config=$config_file op=remove --node=$node.new
 	
 	    if [ $success == "true" ]
 	    then
@@ -119,6 +123,11 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 		    logwrite "Adding the new entry to $parser_config "
 		    logwrite "[$subscribers_dir/$node   $tables_dir/$node.lst]" nl
 		    echo "$subscribers_dir/$node        $tables_dir/$node.lst" >> $parser_config
+
+            # ART LST - Add $node to su_production.slonycfg. At the same time, insert records for $node in
+            # su_production.slonylst. $subscribers_dir/$node, the sitedir, doesn't exit yet, but it will shortly.
+            $kRepDir/subscribe_manage/gentables.pl op=add config=$config_file --node=$node --sitedir=$subscribers_dir --lst=$tables_dir/$node.new.lst
+
 		    logwrite "Moving subscriber directory"
 	                ## remove any log files that might contain duplicates
 	            if [ -f $SMworkDir/slon_counter.$node.txt ]
@@ -136,10 +145,28 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 	            else
 	                logwrite "ERROR:: No $SMworkDir/slon_counter.$node.txt"
 	            fi
+
+            # Create the sitedir
 		    mv -f $subscribers_dir/$node.new $subscribers_dir/$node
 	            
 		    logwrite "Moving subscriber table list"
 		    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+            # ART LST - no need to populate su_production.slonylst for $node. That was done when gentables.pl op=add was called.
+
+
+            if [ $? -ne 0 ]
+            then
+                # If the database table update fails, set the local success variable to
+                # to false (it looks like that variable isn't used after this point
+                # anyway).
+                #
+                # Somehow we have to pass this failure back to subscription_manager.
+                success=false
+                # Need to clean up
+		        logwrite "Unable to update lst tables properly!"
+                rm -rf $subscribers_dir/$node.new
+		        rm -f $tables_dir/$node.new.lst
+            fi
 		else
 			# Success on old site!
 		    logwrite "Subscriber SQL was a success"
@@ -160,14 +187,34 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 	            else
 	                logwrite "NOTE:: No $SMworkDir/slon_counter.$node.txt (only needed if adding series to subscription list)"
 	            fi
+
+            # COPY the newly created log files to $subscribers_dir/$node. Don't move - this is an existing node so its sitdir
+            # might have existing logs.
 		    cp -pr $subscribers_dir/$node.new/* $subscribers_dir/$node
-	            rm -rf $subscribers_dir/$node.new
+            rm -rf $subscribers_dir/$node.new
 		    logwrite "Removing old subscriber table list"
 		    rm -f $tables_dir/$node.lst
 		    logwrite "Moving new subscriber table list to old one"
 		    mv -f $tables_dir/$node.new.lst $tables_dir/$node.lst
+
+            # ART LST - call into perl code to update db-table versions of the .lst files
+            $kRepDir/subscribe_manage/gentables.pl conf=$config_file op=replace --node=$node --lst=$node.new.lst
+
+            if [ $? -ne 0 ]
+            then
+                # If the database table update fails, set the local success variable to
+                # to false (it looks like that variable isn't used after this point
+                # anyway).
+                #
+                # Somehow we have to pass this failure back to subscription_manager.
+                success=false
+
+                # Need to clean up
+                logwrite "Unable to update lst tables properly!"
+                rm -rf $subscribers_dir/$node.new
+		        rm -f $tables_dir/$node.new.lst
+            fi
 		fi
-	
 	    else
 		if [ $new_site == "true" ]
 		then
@@ -177,6 +224,7 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 		    rm -rf $subscribers_dir/$node.new
 		    logwrite "Removing new subscriber table list"
 		    rm -f $tables_dir/$node.new.lst
+            # ART LST - $node.new was already removed from su_production.slonylst in a previous call to gentables.pl
 		else
 			# Failure on old site!
 		    logwrite "Subscriber SQL was not a success"
@@ -184,6 +232,7 @@ cleanup_counter=$(( $cleanup_counter + 1 ))
 		    rm -rf $subscribers_dir/$node.new
 		    logwrite "Removing new subscriber table list"
 		    rm -f $tables_dir/$node.new.lst
+            # ART LST - $node.new was already removed from su_production.slonylst in a previous call to gentables.pl
 		fi
 	    fi
 	
diff --git a/base/drms/replication/subscribe_manage/subscription_update b/base/drms/replication/subscribe_manage/subscription_update
--- a/base/drms/replication/subscribe_manage/subscription_update
+++ b/base/drms/replication/subscribe_manage/subscription_update
@@ -1,6 +1,16 @@
 #!/bin/bash
 pidfile=$0.pid
 
+# ART - my attempt at documenting this:
+#
+#   LST-file management:
+#   If $node is a new site, then all series being subscribed to get written to $node.new.lst. All series
+#   being unsubscribed from are ignored. If $node is an existing site, then all lines in $node.lst are examined.
+#   All items that are not in the unsubscribe list are added to $node.new.lst. The result is that $node.new.lst
+#   contains what it should had we started with $node.lst and made the appropriate additions for series in the
+#   subscribe list, and subtractions for series in the unsubscribe list.
+
+
 #--------------------------------------------------------------------
 # Subscription Update
 # Syntax: ./subscription_update <server configuration file> <node name> <new site (true/false)> <Config File>
@@ -75,6 +85,7 @@ exec >> $logfile 2>&1
 ## The ORDER things get sourced is IMPORTANT!!
 . $kRepDir/subscribe_manage/subscribe_functions
 
+# ART LST - usertables is used in exactly one place.
 usertables=$tables_dir/$node.lst
 
 
@@ -208,8 +219,16 @@ echo "#UPDATE PID:$$" >> $input_file;
 
  done
 
+# ART LST - The previous block of code made sure that aborted attempts to update $node have been cleaned up
+# by removing $node.new.lst from $parser_config, and by removing $node.new.lst. Perform the analogous 
+# clean-up in the db tables. 
+$kRepDir/subscribe_manage/gentables.pl op=remove conf=$config_file --node=$node.new
 
-
+if [ $? -ne 0 ]
+then
+    logecho "ERROR: Failure to clean-up db-table entries for $node.new."
+    exit 1;
+fi
 
 #-------------------------------------------------------------------------
 # Reads the subscription request file into the arrays:
@@ -262,6 +281,9 @@ else
 ## We don't need the copy anymore
 ##	cp -far  $subscribers_dir/$node $subscribers_dir/$node.new
 fi
+
+# ART LST - the new lst file is referred to by both newtablefile and $tables_dir/$node.new.lst in many places.
+# The code creates $node.new.lst
 newtablefile=$tables_dir/$node.new.lst
 logwrite "newtablefile is [$newtablefile]"
 echo > $newtablefile
@@ -275,7 +297,7 @@ newsubscription=0
 #   assumes that the node has specified "subscribe" for all series in $series, and that the node
 #   is a brand new subscriber. This is not a valid
 #   assumption and there should be error checking to catch the error that a node could have 
-#   specified "unsubscribe", even thought the node is a new node. 
+#   specified "unsubscribe", even though the node is a new node. 
 if [ $new_site == "true" ]
 then
 	logwrite "The Subscription request is from a new site"
@@ -284,8 +306,9 @@ then
 	while [ $counter -lt ${#series[*]} ]
 	do
 		logwrite "Adding [${series[$counter]} to $newtablefile"
+                # ART LST - for a single node, add all newly subscribed to series to the new lst file.
 		echo "${series[$counter]}" >> $newtablefile
-
+                
                 # ART - this was missing
                 newsubscription=1
                 
@@ -301,7 +324,8 @@ then
 # First removes subscriptions with the tag "unsubscribe"
 # Second, adds all subscriptions with the tag "subscribe" to the end of the file
 # ART - This section removes from the current node's lst file all series that the node is 
-#   removing from subscription.
+#   removing from subscription, and it adds to the current node's lst file all series
+#   that the node is subscribing to.
 elif [ $new_site == "false" ]
 then
     unsubhappening=0
@@ -309,6 +333,8 @@ then
 
 	# Removes subscriptions if $request[#] is "unsubscribe"
         # usertables is the subscribing node's .lst file
+        # ART - LST FILE
+        # 
 	exec < $usertables
         	while read line
         	do
@@ -363,9 +389,23 @@ logwrite "counter [$counter] [${#series[*]}] request counter [${request[$counter
 				echo $line >> $newtablefile
 			fi
 			
-		done
+		done # end loop over lst file entries.
 
-		
+        # ART LST - At this point, $newtablefile has the set of series to which $node
+        # will be subscribed, if the subscription process succeeds. Replace the node.new's
+        # su_production.slonylst information with the contents of $newtablefile. We must 
+        # have entries from two nodes at this point: $node.lst and $node.new.lst. The 
+        # subscription process keeps slony-log files for both $node and $node.new for 
+        # a period of time. If things go well, it replaces the contents of $node with 
+        # the contets of $node.new.
+        $kRepDir/subscribe_manage/gentables.pl op=replace conf=$config_file --node=$node.new --lst=$newtablefile
+
+        if [ $? -ne 0 ]
+        then
+            logecho "ERROR: Failure to update db-table entries for $node.new."
+            exit 1;
+        fi
+
 	# adds all lines where request = subscribe to the end of the file	
 	counter=0
 	while [ $counter -lt ${#series[*]} ]
@@ -400,7 +440,7 @@ fi
 
 #-------------------------------------------------------------------------
 # Adding the new entry to the slon log parser config file
-# This was added to the sql_gen script, right after sdo_slony1_dump.sh is started
+# This was moved to subscription_cleanup, into the critical region
 #-------------------------------------------------------------------------
 #logwrite "Adding the new entry to $parser_config"
 #logwrite "[$subscribers_dir/$node.new	$newtablefile]" nl
