Modify subscribe_series: it no longer will apply the createns.sql file if the schema of the series being subscribed to is already set up properly

diff --git a/base/drms/scripts/subscribe_series/subscribe_series b/base/drms/scripts/subscribe_series/subscribe_series
--- a/base/drms/scripts/subscribe_series/subscribe_series
+++ b/base/drms/scripts/subscribe_series/subscribe_series
@@ -71,6 +71,31 @@ function logecho {
   fi
 }
 
+function TableExists () {
+    exists=0
+    ns=$1
+    relname=$2
+    seq=$3
+
+    if [ $seq -ne 0 ]
+    then
+        cmd="\ds"
+    else
+        cmd="\dt"
+    fi
+
+    psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -t -c "$cmd $ns.$relname" "$pg_dbname" > sqlcheck.tmp 2>&1
+
+    result=`egrep 'No matching' sqlcheck.tmp`
+
+    if [ -z "$result" ]
+    then
+        exists=1
+    fi
+
+    return $exists
+}
+
 #--------------------------------------------------------------------
 # syntax check
 #--------------------------------------------------------------------
@@ -84,6 +109,9 @@ else
 	echo $error
 	exit
 fi
+
+# extract seriesname from the $subscribe_file file
+series=`awk '{print $1}' "$subscribe_file" | egrep '^[^#[:space:]]'`
 
 . "$config_file"
 
@@ -309,28 +337,158 @@ RM -f "$node.sql.tar.gz"
 # Execute $node.createns.sql
 logecho "Applying SQL file $node.createns.sql to database"
 
-# XXX - ART
 # Add check for slony cluster schema (eg, _jsoc), and don't proceed if it exists
-logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -ef $node.createns.sql $pg_dbname > /dev/null]"
-psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -ef "$node.createns.sql" "$pg_dbname" > /dev/null
+# If entry in admin.ns exists, do not apply createns.sql. However, 
+# we cannot assume that the drms_* tables and sequence exist. If any of these
+# tables is missing, bail.
+#   name - schema of series being subscribed to
+#   owner - PG user that owns this series (should be slony)
 
-logecho "Applying SQL file $node.subscribe_series.sql to database"
-logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -ef $node.subscribe_series.sql $pg_dbname > sqlcheck.tmp 2>&1]"
-psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -ef "$node.subscribe_series.sql" "$pg_dbname" > sqlcheck.tmp 2>&1
+adminnsexist=0
+schemaexist=0
 
-check=`cat sqlcheck.tmp | grep "ERROR:"`
-logwrite "Checking for errors with $node.subscribe_series.sql"
-logwrite "Found errors: [$check]" nl
+nsname=`echo ${series%%.*}`
 
-if [  ! "$check" == "" ] 
+logwrite "seriesname is $series"
+logwrite "series namespace is $nsname"
+
+# Check for schema existence
+logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -t -c SELECT * FROM pg_catalog.pg_namespace WHERE nspname = '$nsname' $pg_dbname]"
+psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -t -c "SELECT * FROM pg_catalog.pg_namespace WHERE nspname = '$nsname'" "$pg_dbname" > sqlcheck.tmp 2>&1
+result=`egrep '.' sqlcheck.tmp`
+if [ ! -z "$result" ]
 then
+    schemaexist=1
+fi
+
+# Check for admin.ns entry existence
+logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -t -c SELECT * FROM admin.ns WHERE name = '$nsname' AND owner = '$pg_user' $pg_dbname]"
+psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -t -c "SELECT * FROM admin.ns WHERE name = '$nsname' AND owner = '$pg_user'" "$pg_dbname" > sqlcheck.tmp 2>&1
+result=`egrep '.' sqlcheck.tmp`
+if [ ! -z "$result" ]
+then
+    adminnsexist=1
+fi
+
+logwrite "table schema check: $schemaexist; schema adminns entry check: $adminnsexist"
+
+# If one or the other exists, then we can't apply createns.sql AND the schema, admin.ns entry, drms_* tables must exist
+check=good
+docreatens=1
+if [ $schemaexist -ne 0 -o $adminnsexist -ne 0 ]
+then
+    docreatens=0
+    if [ $schemaexist -eq 0 -o $adminnsexist -eq 0 ]
+    then
+        check=failed
+        logecho "Missing schema or entry in the admin.ns table; failing."
+    else
+        # Search for tables
+        TableExists $nsname "drms_series" 0
+        result=$?
+
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+        if [ ! $check == "failed" ]
+        then
+            TableExists $nsname "drms_keyword" 0
+            result=$?
+        fi
+        
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+        if [ ! $check == "failed" ]
+        then
+            TableExists $nsname "drms_link" 0
+            result=$?
+        fi
+        
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+        if [ ! $check == "failed" ]
+        then
+            TableExists $nsname "drms_segment" 0
+            result=$?
+        fi
+        
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+        if [ ! $check == "failed" ]
+        then
+            TableExists $nsname "drms_session" 0
+            result=$?
+        fi
+        
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+        if [ ! $check == "failed" ]
+        then
+            TableExists $nsname "drms_sessionid_seq" 1
+            result=$?
+        fi
+        
+        if [ ! $result ]
+        then
+            check=failed
+        fi
+
+         if [ $check == "failed" ]
+         then
+             logecho "Incomplete set of schema drms_* tables; failing."
+         fi
+    fi
+fi
+
+if [ ! $check == "failed" ]
+then
+    if [ $docreatens -ne 0 ]
+    then
+        logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -ef $node.createns.sql $pg_dbname]"
+        psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -ef "$node.createns.sql" "$pg_dbname" > sqlcheck.tmp 2>&1
+        result=`cat sqlcheck.tmp`
+        logwrite $result
+    else
+        logwrite "Check for existing schema $nsname succeeded - no need to apply createns.sql"
+    fi
+
+    logecho "Applying SQL file $node.subscribe_series.sql to database"
+    logwrite "Executing [psql -p $pg_port -h $pg_host -U $pg_user -ef $node.subscribe_series.sql $pg_dbname]"
+    psql -p "$pg_port" -h "$pg_host" -U "$pg_user" -ef "$node.subscribe_series.sql" "$pg_dbname" > sqlcheck.tmp 2>&1
+    result=`cat sqlcheck.tmp`
+    logwrite $result
+
+    check=`cat sqlcheck.tmp | grep "ERROR:"`
+    logwrite "Checking for errors with $node.subscribe_series.sql"
+    logwrite "Found errors: [$check]" nl
+
+    if [  ! "$check" == "" ] 
+    then
 	logwrite "Failed to apply $node.subscribe_series.sql"
 	logwrite "Rolling back to previous state"
 	success=false
-else
+    else
 	logwrite "Application of $node.subscribe_series.sql succeded, continuing"
 	success=true
+    fi
+else
+    success=false;
 fi
+
 RM -f sqlcheck.tmp
 
 if [ $success == "true" ]
@@ -346,6 +504,9 @@ else
 fi
 
 SSH "$webdb_user@$webdb_ip" 'cp -f '"'$webdb_dir/$node.subscribe_series.cfg'"' '"'$webdb_dir/$node.subscribe_series.sqlapplied'"
+
+unset result
+unset check
 
 #--------------------------------------------------------------------
 # Loop waiting for done file to continue (which signifies that manager is done and has cleaned up)
